// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CurrencyController from "./currency_controller"
application.register("currency", CurrencyController)

import FlashController from "./flash_controller"
application.register("flash", FlashController)

import HistoryBackController from "./history_back_controller"
application.register("history-back", HistoryBackController)

import InvoicePreviewController from "./invoice_preview_controller"
application.register("invoice-preview", InvoicePreviewController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)
