// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CurrencyController from "./currency_controller"
application.register("currency", CurrencyController)

import FlashController from "./flash_controller"
application.register("flash", FlashController)
