---
# Omakase Ruby styling for Rails
inherit_gem:
  rubocop-rails-omakase: rubocop.yml

plugins:
  - rubocop-rails
  - rubocop-performance

AllCops:
  TargetRubyVersion: 3.3.9
  TargetRailsVersion: 8.0
  Exclude:
    - '**/node_modules/**/*'
    - '**/vendor/**/*'
# Overwrite or add rules to create your own house style
# Layout/SpaceInsideArrayLiteralBrackets:
#   Enabled: false
