default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: claria_development
  username: claria
  host: localhost

test:
  <<: *default
  database: claria_test
  username: claria
  host: localhost

production:
  <<: *default
  database: <%= ENV.fetch("DB_NAME", "claria_production") %>
  username: <%= ENV.fetch("DB_USER", "claria") %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>
  host: <%= ENV.fetch("DB_HOST", "claria-db") %>
  port: <%= ENV.fetch("DB_PORT", 5432) %>
